# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Build and Publish General Domain package"

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: "Build and Publish General Domain package"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: "Build project"
      run: dotnet build ./GeneralDomain.sln --configuration Release

    - name: "Pack to NuGet"
      run : dotnet pack ./GeneralDomain.sln --configuration Release --output ./packages -p:PackageVersion=1.0.${{github.run_number}}

    - name: "Authenticate to Package Registry"
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: "Publish General Domain package"
      run: dotnet nuget push ./packages/*.nupkg -k ${{ secrets.NUGET_FEED_KEY }} -s "github" 

